# Generated by Django 5.1.6 on 2025-02-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_theme_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='theme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theme'),
        ),
    ]
